# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ShapefileLoader
                                 A QGIS plugin
 To load shapefiles to a canvas
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-02-15
        git sha              : $Format:%H$
        copyright            : (C) 2020 by Group 8
        email                : g8@gmail.coom
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, Qt
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QFileDialog
from qgis.gui import * 
from qgis.core import QgsVectorLayer, QgsProject
from qgis.gui import QgisInterface
from qgis.utils import iface


# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .shapefile_loader_dialog import ShapefileLoaderDialog
import os.path


class ShapefileLoader:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'ShapefileLoader_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Shapefile Loader')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic

        self.vector_layers = []
        self.canvas = QgsMapCanvas()
        self.canvas.setCanvasColor(Qt.white)
        self.vector_layer = ""
        self.lyr = iface.activeLayer()


    def load_and_display_shapefile(self): 

        file_path_list = QFileDialog.getOpenFileName( filter="*.shp", caption="Load Shapefile")
        file_path = file_path_list[0]

        if not file_path == '':
            self.vector_layers = []
            # self.dlg.lineEdit.setText(file_path)
            layer_name_and_extension = os.path.basename(file_path)
            layer_name = os.path.splitext(layer_name_and_extension)[0]
            self.vector_layer = QgsVectorLayer(file_path, layer_name, "ogr")
            self.vector_layers.append(self.vector_layer)
            
            QgsProject.instance().addMapLayer(self.vector_layer)
            self.canvas.setExtent(self.vector_layer.extent())
            self.canvas.setLayers(self.vector_layers)
            self.canvas.show()
        else:
            pass


    def county_identifier(self):

        pass
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('ShapefileLoader', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToVectorMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path_1 = ':/plugins/shapefile_loader/icon_1.png'
        icon_path_2 = ':/plugins/shapefile_loader/icon_2.png'
        self.add_action(
            icon_path_1,
            text=self.tr(u'Shapefile Loader'),
            callback=self.load_and_display_shapefile,
            parent=self.iface.mainWindow())

        self.add_action(
            icon_path_2,
            text=self.tr(u'County Identifier'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginVectorMenu(
                self.tr(u'&Shapefile Loader'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = ShapefileLoaderDialog()

                # self.dlg.lineEdit.setText(file_path)
                

        # show the dialog

        self.dlg.show()
        iface.mapCanvas().refresh()
        layer_name_list = iface.mapCanvas().layers()

        if len(layer_name_list)>0:
            for layer_name_obj in layer_name_list:
                layer_name = layer_name_obj.name()

                if layer_name == "gadm36_KEN_1":
                    features = layer_name_obj.getFeatures()

                    for feat in features:
                        attrs = feat.attributes()
                        group_number = "8"
                        county_number = attrs[8]
                        county_name = attrs[3]

                        if county_number == group_number:
                            text_to_desplay = f"Your are from {county_name} county"
                            self.dlg.label.setText(text_to_desplay)
                            break
                        else:
                            self.dlg.label.setText("Make sure you have gadm36_KEN_1 original shapefile")
                        # Run the dialog event loop
                    break

                else:
                    self.dlg.label.setText("Make sure you have loaded gadm36_KEN_1 shapefiles")
        else:
            self.dlg.label.setText("Make sure you have loaded A shapefile")


        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass
